-- Durable AI Coach rate limiting. Only a service-role Edge Function can
-- consume the limiter; no prompt, response, health value, or training value
-- is stored here.

create table public.coach_request_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index coach_request_events_user_created_idx
  on public.coach_request_events (user_id, created_at desc);

alter table public.coach_request_events enable row level security;

create or replace function public.consume_coach_rate_limit(p_user_id uuid)
returns table (allowed boolean, retry_after_seconds integer)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  minute_count integer;
  day_count integer;
  retry_seconds integer;
begin
  -- Serialize checks per user so concurrent requests cannot race past the
  -- count-and-insert boundary.
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  delete from public.coach_request_events
   where user_id = p_user_id
     and created_at < now() - interval '2 days';

  select count(*)::integer into minute_count
    from public.coach_request_events
   where user_id = p_user_id
     and created_at >= now() - interval '1 minute';

  if minute_count >= 8 then
    select greatest(
      1,
      ceil(extract(epoch from (min(created_at) + interval '1 minute' - now())))::integer
    ) into retry_seconds
      from public.coach_request_events
     where user_id = p_user_id
       and created_at >= now() - interval '1 minute';
    return query select false, coalesce(retry_seconds, 60);
    return;
  end if;

  select count(*)::integer into day_count
    from public.coach_request_events
   where user_id = p_user_id
     and created_at >= now() - interval '24 hours';

  if day_count >= 100 then
    select greatest(
      1,
      ceil(extract(epoch from (min(created_at) + interval '24 hours' - now())))::integer
    ) into retry_seconds
      from public.coach_request_events
     where user_id = p_user_id
       and created_at >= now() - interval '24 hours';
    return query select false, coalesce(retry_seconds, 3600);
    return;
  end if;

  insert into public.coach_request_events (user_id) values (p_user_id);
  return query select true, 0;
end;
$$;

revoke all on table public.coach_request_events from public, anon, authenticated;
revoke all on function public.consume_coach_rate_limit(uuid) from public, anon, authenticated;
grant select on table public.coach_request_events to service_role;
grant execute on function public.consume_coach_rate_limit(uuid) to service_role;
